# Generated by Django 2.1.1 on 2018-09-11 14:23

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0009_alter_user_last_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('user', models.OneToOneField(on_delete='Cascade', primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
                ('state', models.CharField(max_length=100)),
                ('L_G_A', models.CharField(max_length=100)),
                ('address', models.CharField(max_length=100)),
                ('phone', models.IntegerField(default=0)),
            ],
        ),
    ]
