# Generated by Django 2.1.4 on 2018-12-25 17:49

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Blog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('updated', models.DateTimeField(auto_now_add=True)),
                ('author', models.CharField(max_length=50, null=True)),
                ('title', models.CharField(max_length=205)),
                ('image', models.ImageField(null=True, upload_to='blog_image')),
                ('content', models.TextField()),
            ],
        ),
    ]
