# Generated by Django 2.1.1 on 2018-09-03 14:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Blog', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='blog',
            old_name='date',
            new_name='updated',
        ),
    ]
