# Generated by Django 2.1.1 on 2018-12-08 23:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Blog', '0003_subscribemail'),
    ]

    operations = [
        migrations.CreateModel(
            name='Comments',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('image', models.ImageField(blank=True, null=True, upload_to='comment_image')),
                ('email', models.EmailField(max_length=100)),
                ('comment', models.TextField()),
            ],
        ),
    ]
