# Generated by Django 2.1.1 on 2018-12-08 23:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Blog', '0004_comments'),
    ]

    operations = [
        migrations.AddField(
            model_name='subscribemail',
            name='name',
            field=models.CharField(default='guest', max_length=100),
        ),
    ]
