# Generated by Django 2.1.1 on 2018-09-01 00:36

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ReportModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('deviceName', models.CharField(max_length=50)),
                ('deviceModel', models.CharField(max_length=50)),
                ('serialNumber', models.CharField(max_length=100)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('phone', models.CharField(default=0, max_length=15)),
            ],
        ),
    ]
