# Generated by Django 2.1.1 on 2018-09-01 13:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Mylost', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Blog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('author', models.CharField(max_length=50, null=True)),
                ('title', models.CharField(max_length=205)),
                ('image', models.ImageField(null=True, upload_to='blog_image')),
                ('content', models.TextField()),
            ],
        ),
    ]
