# Generated by Django 2.1.1 on 2018-09-02 19:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Mylost', '0003_delete_blog'),
    ]

    operations = [
        migrations.AddField(
            model_name='reportmodel',
            name='state',
            field=models.CharField(default='state', max_length=250),
        ),
        migrations.AlterField(
            model_name='reportmodel',
            name='date',
            field=models.DateField(auto_now=True),
        ),
    ]
