# Generated by Django 2.1.1 on 2018-09-02 19:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Mylost', '0004_auto_20180902_2033'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reportmodel',
            name='date',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
