# Generated by Django 2.1.1 on 2018-09-04 13:20

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('Mylost', '0005_auto_20180902_2034'),
    ]

    operations = [
        migrations.AddField(
            model_name='reportmodel',
            name='status',
            field=models.CharField(choices=[('STOLEN', 'STOLEN'), ('LOST', 'LOST')], default=django.utils.timezone.now, max_length=50),
            preserve_default=False,
        ),
    ]
