# Generated by Django 2.1.1 on 2018-09-04 23:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Mylost', '0006_reportmodel_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='Suggestion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=100)),
                ('message', models.TextField()),
            ],
        ),
        migrations.AlterField(
            model_name='reportmodel',
            name='status',
            field=models.CharField(choices=[('STOLEN', 'STOLEN'), ('LOST', 'LOST')], max_length=50, null=True),
        ),
    ]
