# Generated by Django 2.1.1 on 2018-09-16 19:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Mylost', '0009_suggestion_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reportmodel',
            name='state',
            field=models.CharField(choices=[('STOLEN', 'STOLEN'), ('LOST', 'LOST'), ('MISPLACED', 'MISPLACED')], default='', max_length=250),
        ),
        migrations.AlterField(
            model_name='reportmodel',
            name='status',
            field=models.CharField(choices=[('STOLEN', 'STOLEN'), ('LOST', 'LOST'), ('MISPLACED', 'MISPLACED')], max_length=50, null=True),
        ),
    ]
