# Generated by Django 2.1.1 on 2018-10-05 22:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Mylost', '0012_foundmodel'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='foundmodel',
            name='date',
        ),
        migrations.RemoveField(
            model_name='foundmodel',
            name='deviceModel',
        ),
        migrations.RemoveField(
            model_name='foundmodel',
            name='deviceName',
        ),
        migrations.RemoveField(
            model_name='foundmodel',
            name='email',
        ),
        migrations.RemoveField(
            model_name='foundmodel',
            name='phone',
        ),
        migrations.RemoveField(
            model_name='foundmodel',
            name='serialNumber',
        ),
        migrations.RemoveField(
            model_name='foundmodel',
            name='state',
        ),
        migrations.RemoveField(
            model_name='foundmodel',
            name='status',
        ),
    ]
