# Generated by Django 2.1.1 on 2018-11-16 12:45

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('Mylost', '0013_auto_20181005_2352'),
    ]

    operations = [
        migrations.AddField(
            model_name='reportmodel',
            name='device_status',
            field=models.CharField(choices=[('FOUND', 'FOUND'), ('NOT FOUND', 'NOT FOUND')], default=django.utils.timezone.now, max_length=20),
            preserve_default=False,
        ),
    ]
