# Generated by Django 2.1.1 on 2018-12-06 23:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Mylost', '0015_auto_20181116_1412'),
    ]

    operations = [
        migrations.RenameField(
            model_name='reportmodel',
            old_name='status',
            new_name='condition',
        ),
        migrations.AlterField(
            model_name='reportmodel',
            name='serialNumber',
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
